export const MEASURE_UNITS = [
  { id: "ud", label: "Unidades (ud)" },
  { id: "m2", label: "Metros cuadrados (m²)" },
  { id: "ml", label: "Metros lineales (ml)" },
  { id: "m3", label: "Metros cúbicos (m³)" },
  { id: "kg", label: "Kilogramos (kg)" },
  { id: "l", label: "Litros (l)" },
  { id: "h", label: "Horas (h)" },
  { id: "pa", label: "Partida alzada (pa)" },
] as const;

export const SECTION_ICONS = [
  "🧱",
  "📐",
  "🚿",
  "⚡",
  "🪨",
  "🎨",
  "🔧",
  "🪚",
  "🔩",
  "🪛",
  "🏗️",
  "🏠",
  "🚪",
  "🪟",
  "🛁",
  "🚽",
  "💡",
  "🔌",
  "🧹",
  "🪣",
  "🧰",
  "⚙️",
  "🔨",
  "📏",
  "🪜",
] as const;
